### ISSUE TITLE
Forge Ore Dictionary Error

### ISSUE THREAD

**Issue by damonmensch** [MrComputerGhost/Runic-Dungeons#27]
Ore dictionary is complaining about your attempt to register an item.

09:10:30  [Warn] [FML]: ****************************************
09:10:30  [Warn] [FML]: \* A broken ore dictionary registration with name ingotRunicSteel has occurred. It adds an item (type: class mrcomputerghost.runicdungeons.items.ItemCraftingItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.TO USERS: YES this is a BUG in the mod Runic Dungeons report it to them!
09:10:30  [Warn] [FML]: \* at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:507)
09:10:30  [Warn] [FML]: \* at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:474)
09:10:30  [Warn] [FML]: \* at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:472)
09:10:30  [Warn] [FML]: \* at mrcomputerghost.runicdungeons.items.RunicItems.initItems(RunicItems.java:136)
09:10:30  [Warn] [FML]: \* at mrcomputerghost.runicdungeons.RunicDungeons.preInit(RunicDungeons.java:119)
09:10:30  [Warn] [FML]: \* at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
09:10:30  [Warn] [FML]: ****************************************

**Comment by Tencao** [comment]
Can also confirm this bug

**Comment by MrComputerGhost** [comment]
Thank you, this will be fixed in the next release.
