### ISSUE TITLE
OreDirectionary before GameRegistry

### ISSUE THREAD

**Issue by PssbleTrngle** [MrComputerGhost/Runic-Dungeons#38]
My launcher say that the "ingotRunicSteel" oreDirr for one of your items is registered before the item itself, so the game doesn't know the item.

See on you own:

`[10:19:23] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name ingotRunicSteel has occurred. It adds an item (type: class mrcomputerghost.runicdungeons.items.ItemCraftingItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Runic Dungeons report it to them!
[10:19:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[10:19:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[10:19:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:499)
[10:19:23] [Client thread/WARN] [FML]: *  at mrcomputerghost.runicdungeons.items.RunicItems.initItems(RunicItems.java:136)
[10:19:23] [Client thread/WARN] [FML]: *  at mrcomputerghost.runicdungeons.RunicDungeons.preInit(RunicDungeons.java:119)
[10:19:23] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...`

**Comment by MrComputerGhost** [comment]
Fixed.
