### ISSUE TITLE
Crashing Badly

### ISSUE THREAD

**Issue by NeonNobility** [MrComputerGhost/Runic-Dungeons#54]
I'm using v1.1.7b for Minecraft 1.7.10 and getting this wall of text in my crash logs every time I try to start the game

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/27/20 6:53 PM
Description: Initializing game

java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78471_a(FJ)V @429: dload
  Reason:
    Local index 17 is invalid
  Bytecode:
    0x0000000: b803 8d36 0415 0499 000c 2ab4 00e4 2320
    0x0000010: b805 cb23 3805 2ab4 00e4 b404 3d13 043f
    0x0000020: b604 442a b403 f399 0008 2a23 b604 ce11
    0x0000030: 0b44 b803 e011 0b71 b803 e011 0bc0 b803
    0x0000040: e011 0204 1301 ccb8 053b 2ab4 00e4 b401
    0x0000050: a8c7 0011 2ab4 00e4 2ab4 00e4 b401 acb5
    0x0000060: 01a8 2ab4 00e4 b404 3d13 05cd b605 372a
    0x0000070: 23b6 05cf 2ab4 00e4 b401 a83a 062a b400
    0x0000080: e4b4 0399 3a07 2ab4 00e4 b405 d33a 0819
    0x0000090: 06b4 05d6 1906 b401 b519 06b4 05d6 6723
    0x00000a0: 8d6b 6339 0919 06b4 05d9 1906 b401 be19
    0x00000b0: 06b4 05d9 6723 8d6b 6339 0b19 06b4 05dc
    0x00000c0: 1906 b401 c119 06b4 05dc 6723 8d6b 6339
    0x00000d0: 0d2a b400 e4b4 043d 1305 deb6 0537 0336
    0x00000e0: 0f15 0f05 a207 7b15 0f36 102a b400 e4b4
    0x00000f0: 018a b403 3499 001f 150f b305 e4b2 05e4
    0x0000100: 9a00 0d03 0404 03b8 05e8 a700 0a04 0303
    0x0000110: 03b8 05e8 1504 9900 0905 2320 b805 ec2a
    0x0000120: b400 e4b4 043d 1305 eeb6 0537 1504 9900
    0x0000130: 1903 032a b400 e4b4 014d 2ab4 00e4 b401
    0x0000140: 50b8 05f1 a700 1603 032a b400 e4b4 014d
    0x0000150: 2ab4 00e4 b401 50b8 0552 2a23 b605 f411
    0x0000160: 4100 b805 5815 0499 0006 b805 f711 0b44
    0x0000170: b803 e02a b400 e4b4 043d 1305 f9b6 0537
    0x0000180: 2a23 150f b605 fb15 0499 0007 23b8 05fe
    0x0000190: 2ab4 00e4 b401 ac2a b400 e4b4 018a b403
    0x00001a0: a205 a000 0704 a700 0403 b806 0218 11b2
    0x00001b0: 0605 8d63 3911 1809 b206 088d 6339 0918
    0x00001c0: 0bb2 060b 8d63 390b 2ab4 00e4 b404 3d13
    0x00001d0: 060d b605 37b8 0613 57b8 0618 b806 1b9a
    0x00001e0: 000f b806 1e9a 0009 b806 2199 0035 b206
    0x00001f0: 249a 002f 2a02 23b6 0627 2ab4 00e4 b404
    0x0000200: 3d13 0629 b605 3715 0499 0006 b806 2c19
    0x0000210: 0723 b606 2f15 0499 000f b806 32a7 0009
    0x0000220: 110b e2b8 03cb 110b 60b8 03e0 2a04 23b6
    0x0000230: 0627 2ab4 00e4 b401 8ab4 0635 9900 0911
    0x0000240: 1d01 b806 382a b400 e4b4 043d 1306 3ab6
    0x0000250: 0537 bb06 3c59 b706 3d3a 1315 0499 000e
    0x0000260: 1913 1809 180b 180d b806 4119 1318 0918
    0x0000270: 0b18 0db6 0644 2ab4 00e4 b403 9919 1323
    0x0000280: b606 4815 0f9a 005f b803 8d99 0006 b806
    0x0000290: 4b2a 59b4 064d 0460 b506 4d2a b400 e4b4
    0x00002a0: 043d 1306 4fb6 0537 2ab4 00e4 b403 9919
    0x00002b0: 0603 b606 539a 0026 2009 9499 0020 20b8
    0x00002c0: 0532 6537 1416 1409 949b 0012 1614 1406
    0x00002d0: 5494 9e00 06a7 0006 a7ff d0b8 038d 9900
    0x00002e0: 06b8 0658 1906 b401 be14 0659 989c 000a
    0x00002f0: 2a19 0723 b606 5e2a b400 e4b4 043d 1306
    0x0000300: 60b6 0537 2a03 23b6 0627 110b 60b8 03e0
    0x0000310: 2ab4 00e4 b600 ecb2 0665 b603 d6b8 066a
    0x0000320: 2ab4 00e4 b404 3d13 066c b605 3711 1700
    0x0000330: b803 2db8 0395 b803 8d99 0006 b806 6f19
    0x0000340: 0719 0603 238d b606 7357 b803 8d99 0006
    0x0000350: b806 7611 1d00 b806 3811 0204 1301 ccb8
    0x0000360: 053b b206 7ab6 067d 3616 2ab4 0292 9a01
    0x0000370: 1111 1700 b803 2db8 03bb b803 95b8 0680
    0x0000380: 2ab4 00e4 b404 3d13 0682 b605 3715 1699
    0x0000390: 0014 b206 8504 bd00 0459 0303 b805 6553
    0x00003a0: b806 8919 0719 0619 1323 b606 8d15 1699
    0x00003b0: 0014 b206 8504 bd00 0459 0302 b805 6553
    0x00003c0: b806 89b8 066a 2a23 8db6 03b8 1117 00b8
    0x00003d0: 032d b803 bbb8 0395 2ab4 00e4 b402 00c6
    0x00003e0: 00a0 1906 b202 d0b6 0691 9900 9519 06c1
    0x00003f0: 02f1 9900 8d2a b400 e4b4 018a b403 a89a
    0x0000400: 0080 1906 c002 f13a 1711 0bc0 b803 cb2a
    0x0000410: b400 e4b4 043d 1306 93b6 0537 1516 9900
    0x0000420: 3eb2 0696 1006 bd00 0459 0319 0753 5904
    0x0000430: 1917 5359 052a b400 e4b4 0200 5359 0603
    0x0000440: b805 6553 5907 1917 b406 9ab6 06a0 5359
    0x0000450: 0823 b805 6a53 b806 a39a 0020 2ab4 00e4
    0x0000460: b401 8ab4 03a8 9a00 1319 0719 172a b400
    0x0000470: e4b4 0200 0323 b606 a711 0bc0 b803 e011
    0x0000480: 1700 b803 2db8 03bb 2ab4 00cd 0f97 9a00
    0x0000490: aa19 06c1 02f1 9900 a22a b400 e4b4 018a
    0x00004a0: b403 a89a 0095 2ab4 00e4 b402 00c6 008b
    0x00004b0: 1906 b202 d0b6 0691 9a00 8019 06c0 02f1
    0x00004c0: 3a17 110b c0b8 03cb 2ab4 00e4 b404 3d13
    0x00004d0: 0693 b605 3715 1699 003e b206 9610 06bd
    0x00004e0: 0004 5903 1907 5359 0419 1753 5905 2ab4
    0x00004f0: 00e4 b402 0053 5906 03b8 0565 5359 0719
    0x0000500: 17b4 069a b606 a053 5908 23b8 056a 53b8
    0x0000510: 06a3 9a00 202a b400 e4b4 018a b403 a89a
    0x0000520: 0013 1907 1917 2ab4 00e4 b402 0003 23b6
    0x0000530: 06a7 110b c0b8 03e0 2ab4 00e4 b404 3d13
    0x0000540: 06a9 b605 3711 0be2 b803 e011 0302 0404
    0x0000550: 03b8 06ac 1907 b206 b219 0623 b606 b611
    0x0000560: 0be2 b803 cb2a b402 929a 005a 2a23 8db6
    0x0000570: 03ac 2ab4 00e4 b404 3d13 06b8 b605 3715
    0x0000580: 0499 0006 b806 bb19 0819 0623 b606 bfb8
    0x0000590: 066a 2a03 23b6 0627 2ab4 00e4 b404 3d13
    0x00005a0: 06c1 b605 3715 0499 0006 b806 c419 0819
    0x00005b0: 0623 b606 c715 0499 0006 b806 ca2a 238d
    0x00005c0: b603 b803 b806 cd11 0b44 b803 e02a b400
    0x00005d0: e4b4 043d 1306 cfb6 0537 1504 9900 06b8
    0x00005e0: 06d2 2a23 b606 d515 0499 0006 b806 d804
    0x00005f0: b806 cd15 0499 000c 2a23 05b8 06dc b806
    0x0000600: df11 0be2 b803 cb11 0b44 b803 e011 0302
    0x0000610: 1103 0304 03b8 06ac 1102 0413 01cc b805
    0x0000620: 3b2a 0323 b606 2711 0be2 b803 e003 b806
    0x0000630: cd2a b400 e4b6 00ec b206 65b6 03d6 b806
    0x0000640: e4b8 06e7 9900 9c2a b400 e4b4 043d 1306
    0x0000650: e9b6 0537 2ab4 00e4 b401 8ab4 0635 9900
    0x0000660: 0911 1d01 b806 3811 0be2 b803 e011 0302
    0x0000670: 1103 0304 03b8 06ac 2ab4 00e4 b401 8ab4
    0x0000680: 0334 9900 36b2 05e4 9a00 0d03 0404 04b8
    0x0000690: 05e8 a700 0a04 0303 04b8 05e8 1504 9900
    0x00006a0: 06b8 06ec 1907 0423 8db6 06f0 5715 0499
    0x00006b0: 0022 b806 f3a7 001c 1504 9900 06b8 06ec
    0x00006c0: 1907 0423 8db6 06f0 5715 0499 0006 b806
    0x00006d0: f311 0be2 b803 cb11 1d00 b806 38a7 0029
    0x00006e0: 2ab4 00e4 b404 3d13 06e9 b605 3715 0499
    0x00006f0: 0006 b806 ec19 0704 238d b606 f057 1504
    0x0000700: 9900 06b8 06f3 b806 f615 1699 004e 2ab4
    0x0000710: 0292 9a00 47b8 0680 2ab4 00e4 b404 3d13
    0x0000720: 0682 b605 37b2 0685 04bd 0004 5903 04b8
    0x0000730: 0565 53b8 0689 2ab4 00e4 b403 9919 0619
    0x0000740: 1323 b606 8db2 0685 04bd 0004 5903 02b8
    0x0000750: 0565 53b8 0689 b806 6a04 b806 cd11 0b44
    0x0000760: b803 e011 0be2 b803 cb11 0b60 b803 cb19
    0x0000770: 06b4 01be 1406 592a b400 e4b4 018a b406
    0x0000780: f913 0335 6a8d 6397 9b00 172a b400 e4b4
    0x0000790: 043d 1306 fbb6 0537 2a19 0723 b606 5e15
    0x00007a0: 1699 0026 2ab4 00e4 b404 3d13 06fd b605
    0x00007b0: 37b2 0700 05bd 0004 5903 1907 5359 0423
    0x00007c0: b805 6a53 b806 892a b400 e4b4 043d 1307
    0x00007d0: 02b6 0537 b207 0506 bd00 0459 032a b400
    0x00007e0: e4b4 0399 5359 0423 b805 6a53 5905 150f
    0x00007f0: b805 6553 b806 a336 1815 189a 003e 2ab4
    0x0000800: 00cd 0f97 9a00 35b2 0624 9a00 2f15 0499
    0x0000810: 000d 2a23 1510 b807 08b8 070b 1101 00b8
    0x0000820: 0558 1504 9900 0e2a 1705 1510 b807 0ea7
    0x0000830: 000a 2a23 150f b607 1015 0499 0006 b807
    0x0000840: 132a b400 e4b4 018a b403 349a 000e 2ab4
    0x0000850: 00e4 b404 3db6 04d1 b184 0f01 a7f8 8504
    0x0000860: 0404 03b8 05e8 2ab4 00e4 b404 3db6 04d1
    0x0000870: b1                                     
  Stackmap Table:
    append_frame(@19,Integer)
    append_frame(@47,Float)
    same_frame(@98)
    full_frame(@225,{Object[#2],Float,Long,Integer,Float,Object[#434],Object[#1504],Object[#1506],Double,Double,Double,Integer},{})
    append_frame(@269,Integer)
    same_frame(@276)
    same_frame(@287)
    same_frame(@327)
    same_frame(@346)
    same_frame(@365)
    same_frame(@400)
    same_locals_1_stack_item_frame(@425,Object[#646])
    full_frame(@426,{Object[#2],Float,Long,Integer,Float,Object[#434],Object[#1504],Object[#1506],Double,Double,Double,Integer,Integer},{Object[#646],Integer})
    append_frame(@494,Double)
    same_frame(@527)
    same_frame(@544)
    same_frame(@550)
    same_frame(@581)
    append_frame(@619,Object[#1596])
    same_frame(@657)
    same_frame(@680)
    append_frame(@728,Long)
    chop_frame(@731,1)
    same_frame(@740)
    same_frame(@759)
    same_frame_extended(@831)
    same_frame(@851)
    append_frame(@931,Top,Top,Integer)
    same_frame(@963)
    append_frame(@1116,Object[#753])
    same_frame(@1145)
    chop_frame(@1151,1)
    append_frame(@1301,Object[#753])
    same_frame(@1330)
    chop_frame(@1336,1)
    same_frame_extended(@1415)
    same_frame(@1453)
    same_frame(@1469)
    same_frame(@1475)
    same_frame(@1506)
    same_frame(@1519)
    same_frame(@1537)
    same_frame_extended(@1639)
    same_frame(@1685)
    same_frame(@1692)
    same_frame(@1700)
    same_frame(@1720)
    same_frame(@1728)
    same_frame(@1745)
    same_frame(@1760)
    same_frame(@1781)
    same_frame(@1798)
    same_frame_extended(@1881)
    same_frame_extended(@1951)
    same_frame(@1991)
    append_frame(@2076,Top,Integer)
    same_frame(@2098)
    same_frame(@2105)
    same_frame(@2113)
    same_frame(@2137)
    full_frame(@2143,{Object[#2],Float,Long,Integer,Float,Object[#434],Object[#1504],Object[#1506],Double,Double,Double,Integer},{})

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Saftsalat1234** [comment]
use RunicDungeons-1.1.3.jar should be fixed there :))
